# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio          = [ 1, 2, 3 ]
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
sort_translit  = false
linemode       = "size"
show_hidden    = false
show_symlink   = false
# scrolloff      = 5
mouse_events   = [ "click", "scroll" ]
title_format   = "Yazi: {cwd}"

[preview]
tab_size        = 2
max_width       = 1000
max_height      = 1500
cache_dir       = ""
image_filter    = "triangle"
image_quality   = 75
sixel_fraction  = 15
ueberzug_scale  = 4
ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]
open = [
  { run = 'opener "$@"', orphan = true, desc = "Open" },
]
play = [
  { run = 'mpv --no-terminal "$@" &', orphan = true, for = "unix" },
]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
]
music = [
	{ run = 'ncmpcpp "$@"', orphan = true, for = "unix" },
]
pdf = [
	{ run = 'zathura "$@"', orphan = true, for = "unix" },
]
document = [
	{ run = 'libreoffice "$@"', orphan = true, for = "unix" },
]
view = [
  { run = '''nsxiv -a "$1" "$(dirname "$1")"/*''', orphan = true, for = "unix" },
]
archiveZip = [
	{ run = 'unzip "$@" &', orphan = true, for = "unix" },
]
archiveTar = [
	{ run = 'unzip "$@" &', orphan = true, for = "unix" },
]
archiveRar = [
	{ run = 'unzip "$@" &', orphan = true, for = "unix" },
]

[open]
rules = [
  # -- Scripts and Code Files
  { name = "*.txt", use = [ "edit" ] },
  { name = "*.csv", use = [ "edit" ] },
  { name = "*.py", use = [ "edit" ] },
  { name = "*.js", use = [ "edit" ] },
  { name = "*.ts", use = [ "edit" ] },
  { name = "*.html", use = [ "edit" ] },
  { name = "*.css", use = [ "edit" ] },
  { name = "*.scss", use = [ "edit" ] },
  { name = "*.sass", use = [ "edit" ] },
  { name = "*.json", use = [ "edit" ] },
  { name = "*.xml", use = [ "edit" ] },
  { name = "*.yaml", use = [ "edit" ] },
  { name = "*.toml", use = [ "edit" ] },
  { name = "*.md", use = [ "edit" ] },
  { name = "*.sh", use = [ "edit" ] },
  { name = "*.bash", use = [ "edit" ] },
  { name = "*.cpp", use = [ "edit" ] },
  { name = "*.c", use = [ "edit" ] },
  { name = "*.h", use = [ "edit" ] },
  { name = "*.java", use = [ "edit" ] },
  { name = "*.go", use = [ "edit" ] },
  { name = "*.rb", use = [ "edit" ] },
  { name = "*.php", use = [ "edit" ] },

  # -- Audio and Music Files
  { name = "*.mp3", use = [ "music" ] },
  { name = "*.wav", use = [ "music" ] },
  { name = "*.flac", use = [ "music" ] },
  { name = "*.aac", use = [ "music" ] },
  { name = "*.ogg", use = [ "music" ] },
  { name = "*.wma", use = [ "music" ] },
  { name = "*.m4a", use = [ "music" ] },

  # -- Video Files
  { name = "*.mp4", use = [ "play" ] },
  { name = "*.webm", use = [ "play" ] },
  { name = "*.mkv", use = [ "play" ] },
  { name = "*.avi", use = [ "play" ] },
  { name = "*.mov", use = [ "play" ] },
  { name = "*.flv", use = [ "play" ] },
  { name = "*.wmv", use = [ "play" ] },

  # -- Image Files
  { name = "*.png", use = [ "view" ] },
  { name = "*.jpg", use = [ "view" ] },
  { name = "*.jpeg", use = [ "view" ] },
  { name = "*.gif", use = [ "view" ] },
  { name = "*.bmp", use = [ "view" ] },
  { name = "*.tiff", use = [ "view" ] },
  { name = "*.svg", use = [ "view" ] },
  { name = "*.webp", use = [ "view" ] },
  { name = "*.ico", use = [ "view" ] },

  # -- Document Files
  { name = "*.doc", use = [ "document" ] },
  { name = "*.docx", use = [ "document" ] },
  { name = "*.xlsx", use = [ "document" ] },
  { name = "*.pptx", use = [ "document" ] },
  { name = "*.odt", use = [ "document" ] },
  { name = "*.ods", use = [ "document" ] },
  { name = "*.rtf", use = [ "document" ] },
  { name = "*.epub", use = [ "document" ] },
  { name = "*.mobi", use = [ "document" ] },
  { name = "*.azw3", use = [ "document" ] },

  #zathura
  { name = "*.pdf", use = [ "pdf" ] },
  { name = "*.cbz", use = [ "pdf" ] },

  # -- Archive Files
  { name = "*.zip", use = [ "archiveZip" ] },
  { name = "*.tgz", use = [ "archive" ] },

  #tar
  { name = "*.tar", use = [ "archiveTar" ] },
  { name = "*.tar.gz", use = [ "archiveTar" ] },

  #rar
  { name = "*.rar", use = [ "archiveRar" ] },

  
  #--Fallback
  { name = "*", use = [ "edit" ] },

]

[tasks]
micro_workers    = 10
macro_workers    = 25
bizarre_retry    = 5
image_alloc      = 536870912  # 512MB
image_bound      = [ 0, 0 ]
suppress_preload = false

[plugin]

fetchers = [
    # Mimetype
    { id = "mime", name = "*", run = "mime", if = "!mime", prio = "high" },
]
preloaders = [
    # Image
    { mime = "image/{avif,hei?,jxl,svg+xml}", run = "magick" },
    { mime = "image/*", run = "image" },
    # Video
    { mime = "video/*", run = "video" },
    # PDF
    { mime = "application/pdf", run = "pdf" },
    # Font
    { mime = "font/*", run = "font" },
    { mime = "application/vnd.ms-opentype", run = "font" },
]
previewers = [
    { name = "*/", run = "folder", sync = true },
    # Code
    { mime = "text/*", run = "code" },
    { mime = "*/{xml,javascript,x-wine-extension-ini}", run = "code" },
    # JSON
    { mime = "application/{json,x-ndjson}", run = "json" },
    # Image
    { mime = "image/{avif,hei?,jxl,svg+xml}", run = "magick" },
    { mime = "image/*", run = "image" },
    # Video
    { mime = "video/*", run = "video" },
    # PDF
    { mime = "application/pdf", run = "pdf" },
    # Archive
    { mime = "application/{,g}zip", run = "archive" },
    { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar,iso9660-image}", run = "archive" },
    # Font
    { mime = "font/*", run = "font" },
    { mime = "application/vnd.ms-opentype", run = "font" },
    # Empty file
    { mime = "inode/x-empty", run = "empty" },
    # Fallback
    { name = "*", run = "file" },
]

[input]
# cd
cd_title  = "Change directory:"
cd_origin = "top-center"
cd_offset = [ 0, 2, 50, 3 ]

# create
create_title  = ["Create:", "Create (dir):"]
create_origin = "top-center"
create_offset = [ 0, 2, 50, 3 ]

# rename
rename_title  = "Rename:"
rename_origin = "hovered"
rename_offset = [ 0, 1, 50, 3 ]

# trash
trash_title     = "Move {n} selected file{s} to trash? (y/N)"
trash_origin    = "top-center"
trash_offset    = [ 0, 2, 50, 3 ]

# delete
delete_title    = "Delete {n} selected file{s} permanently? (y/N)"
delete_origin   = "top-center"
delete_offset   = [ 0, 2, 50, 3 ]

# filter
filter_title  = "Filter:"
filter_origin = "top-center"
filter_offset = [ 0, 2, 50, 3 ]

# find
find_title  = [ "Find next:", "Find previous:" ]
find_origin = "top-center"
find_offset = [ 0, 2, 50, 3 ]

# search
search_title  = "Search via {n}:"
search_origin = "top-center"
search_offset = [ 0, 2, 50, 3 ]

# shell
shell_title  = [ "Shell:", "Shell (block):" ]
shell_origin = "top-center"
shell_offset = [ 0, 2, 50, 3 ]

# overwrite
overwrite_title  = "Overwrite an existing file? (y/N)"
overwrite_origin = "top-center"
overwrite_offset = [ 0, 2, 50, 3 ]

# quit
quit_title  = "{n} task{s} running, sure to quit? (y/N)"
quit_origin = "top-center"
quit_offset = [ 0, 2, 50, 3 ]

[select]
open_title  = "Open with:"
open_origin = "hovered"
open_offset = [ 0, 1, 50, 7 ]

[which]
sort_by        = "none"
sort_sensitive = false
sort_reverse   = false
sort_translit  = false

[log]
enabled = false
